# Data Cleaning with Pandas

https://www.kaggle.com/datasets/soniaaaaaaaa/employment-of-india-cleaned-and-messy-data?select=Messy_Employment_India_Dataset.csv

🟦 Cell 1: Import Required Libraries

In [ ]:
import pandas as pd
import numpy as np

🟦 Cell 2: Load the CSV File

In [ ]:
df = pd.read_csv("/content/Messy_Employment_India_Dataset.csv")

🟦 Cell 3: View the Dataset

In [ ]:
df.head(10)

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,NaN,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,NaN,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023
5,Unemployed,25_34,PhD,Tech,Bangalore,HIGH,NaN,54500.0,1/6/2023
6,employed,35 - 44,Master,NaN,Mumbai,moderate,20.0,136500.0,1/7/2023
7,unemployed,35 - 44,Master,NaN,rural,Low,28.0,25300.0,1/8/2023
8,employed,35 - 44,Ph.D,Retail,NaN,Medium,0.0,103600.0,1/9/2023
9,unemployed,55+,Ph.D,Tech,NaN,NaN,3.0,126500.0,1/10/2023

In [ ]:
#for last 5 rows
df.tail()

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
1995,employed,25-34,Ph.D,Finance,Hyderabad,Low,NaN,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,NaN,NaN,22.0,102200.0,6/19/2028
1997,NaN,35 - 44,Masters,Education,NaN,low,NaN,31600.0,6/20/2028
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.0,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,NaN,NaN,moderate,NaN,43300.0,6/22/2028

In [ ]:
df.columns

Index(['Status', 'Age Group', 'Education', 'Industry', 'Location', 'AI Risk',
       'Years of Experience', 'Monthly Salary (INR)', 'Date Recorded'],
      dtype='object')

🟦 Cell 4: Understand Dataset Structure

In [ ]:
df.shape      # number of rows and columns

(2000, 9)

In [ ]:
df.info()     # data types and missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Status                1732 non-null   object
 1   Age Group             1768 non-null   object
 2   Education             1804 non-null   object
 3   Industry              1799 non-null   object
 4   Location              1787 non-null   object
 5   AI Risk               1716 non-null   object
 6   Years of Experience   980 non-null    float64
 7   Monthly Salary (INR)  1613 non-null   float64
 8   Date Recorded         2000 non-null   object
dtypes: float64(2), object(7)
memory usage: 140.8+ KB

In [ ]:
df.describe().T# statistical summary

,count,mean,std,min,25%,50%,75%,max
Years of Experience,980.0,15.244898,9.103941,0.0,7.0,16.0,23.0,30.0
Monthly Salary (INR),1613.0,76886.360818,41628.008054,5100.0,40700.0,77200.0,112400.0,149900.0

🟦 Cell 5: Check Missing Values

In [ ]:
df.isnull()

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,False,False,False,False,False,True,True,False,False
1,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
1995,False,False,False,False,False,False,True,False,False
1996,False,False,False,False,True,True,False,False,False
1997,True,False,False,False,True,False,True,False,False
1998,False,False,False,False,False,False,False,False,False
1999,False,False,False,True,True,False,True,False,False

In [ ]:
df.isnull().sum()

Status                   268
Age Group                232
Education                196
Industry                 201
Location                 213
AI Risk                  284
Years of Experience     1020
Monthly Salary (INR)     387
Date Recorded              0
dtype: int64

🟦 Cell 6: Handle Missing Values

Fill missing numerical values with mean

In [ ]:
df['Years of Experience'] = df['Years of Experience'].fillna(df['Years of Experience'].mean())

In [ ]:
df

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,15.244898,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,15.244898,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.000000,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.000000,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.000000,19500.0,1/5/2023
...,...,...,...,...,...,...,...,...,...
1995,employed,25-34,Ph.D,Finance,Hyderabad,Low,15.244898,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,NaN,NaN,22.000000,102200.0,6/19/2028
1997,NaN,35 - 44,Masters,Education,NaN,low,15.244898,31600.0,6/20/2028
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.000000,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,NaN,NaN,moderate,15.244898,43300.0,6/22/2028

Fill missing categorical values

In [ ]:
df['Location'] = df['Location'].fillna("Unknown")

In [ ]:
df

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,15.244898,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,15.244898,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.000000,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.000000,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.000000,19500.0,1/5/2023
...,...,...,...,...,...,...,...,...,...
1995,employed,25-34,Ph.D,Finance,Hyderabad,Low,15.244898,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,Unknown,NaN,22.000000,102200.0,6/19/2028
1997,NaN,35 - 44,Masters,Education,Unknown,low,15.244898,31600.0,6/20/2028
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.000000,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,NaN,Unknown,moderate,15.244898,43300.0,6/22/2028

🟦 Cell 7: Remove Duplicate Rows

In [ ]:
df = df.drop_duplicates()

🟦 Cell 8: Check and Fix Data Types

In [ ]:
df.dtypes

Status                   object
Age Group                object
Education                object
Industry                 object
Location                 object
AI Risk                  object
Years of Experience     float64
Monthly Salary (INR)    float64
Date Recorded            object
dtype: object

In [ ]:
df['Age Group'] = df['Age Group'].astype(int)

ValueError: invalid literal for int() with base 10: '18-24'

🟦 Cell 9: Rename Columns (Optional)

In [ ]:
df = df.rename(columns={
    'Years of Experience': 'YOF',
    'Location': 'Loc'
})

In [ ]:
df

,Status,Age Group,Education,Industry,Loc,AI Risk,YOF,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,15.244898,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,15.244898,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.000000,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.000000,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.000000,19500.0,1/5/2023
...,...,...,...,...,...,...,...,...,...
1995,employed,25-34,Ph.D,Finance,Hyderabad,Low,15.244898,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,Unknown,NaN,22.000000,102200.0,6/19/2028
1997,NaN,35 - 44,Masters,Education,Unknown,low,15.244898,31600.0,6/20/2028
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.000000,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,NaN,Unknown,moderate,15.244898,43300.0,6/22/2028

🟦 Cell 10: Handle Outliers (Simple Filtering)

In [ ]:
df_sort = df[df['Monthly Salary (INR)'] < 10000]
df_sort.head()

,Status,Age Group,Education,Industry,Loc,AI Risk,YOF,Monthly Salary (INR),Date Recorded
41,employed,25-34,Bachelor's,Fintech,Delhi,Low,25.000000,7700.0,2/11/2023
97,Employed,25_34,Ph.D,NaN,urban,High,2.000000,8900.0,4/8/2023
114,Employed,25-34,Masters,Education,suburban,low,15.000000,7600.0,4/25/2023
118,NaN,25_34,NaN,Finance,Urban,Medium,15.244898,5400.0,4/29/2023
141,EMPLOYED,18-24,Diploma,Healthcare,Delhi,HIGH,15.244898,8000.0,5/22/2023

🟦 Cell 11: Clean Text Data

In [ ]:
#Removes extra spaces from the beginning and end of each city name.
df['Education'] = df['Education'].str.strip()
#Converts all city names to lowercase letters.
df['Loc'] = df['Loc'].str.lower()

🟦 Cell 12: Data Validation

In [ ]:
df = df[df['YOF'] > 0]
#df = df[(df['Age'] > 0) & (df['Age'] <= 120)]
df

,Status,Age Group,Education,Industry,Loc,AI Risk,YOF,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,urban,NaN,15.244898,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,15.244898,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,delhi,Low,16.000000,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,urban,Low,30.000000,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,hyderabad,low,9.000000,19500.0,1/5/2023
...,...,...,...,...,...,...,...,...,...
1995,employed,25-34,Ph.D,Finance,hyderabad,Low,15.244898,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,unknown,NaN,22.000000,102200.0,6/19/2028
1997,NaN,35 - 44,Masters,Education,unknown,low,15.244898,31600.0,6/20/2028
1998,EMPLOYED,25_34,high school,Retail,mumbai,HIGH,22.000000,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,NaN,unknown,moderate,15.244898,43300.0,6/22/2028

🟦 Cell 13: Final Check

In [ ]:
df.head()

,Status,Age Group,Education,Industry,Loc,AI Risk,YOF,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,urban,NaN,15.244898,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,15.244898,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,delhi,Low,16.000000,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,urban,Low,30.000000,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,hyderabad,low,9.000000,19500.0,1/5/2023

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1965 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Status                1702 non-null   object
 1   Age Group             1738 non-null   object
 2   Education             1775 non-null   object
 3   Industry              1767 non-null   object
 4   Loc                   1965 non-null   object
 5   AI Risk               1684 non-null   object
 6   YOF                   1965 non-null   float64
 7   Monthly Salary (INR)  1582 non-null   float64
 8   Date Recorded         1965 non-null   object
dtypes: float64(2), object(7)
memory usage: 218.1+ KB

🟦 Cell 14: Save Cleaned Data

In [ ]:
df

,Status,Age Group,Education,Industry,Loc,AI Risk,YOF,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,urban,NaN,15.244898,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,15.244898,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,delhi,Low,16.000000,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,urban,Low,30.000000,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,hyderabad,low,9.000000,19500.0,1/5/2023
...,...,...,...,...,...,...,...,...,...
1995,employed,25-34,Ph.D,Finance,hyderabad,Low,15.244898,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,unknown,NaN,22.000000,102200.0,6/19/2028
1997,NaN,35 - 44,Masters,Education,unknown,low,15.244898,31600.0,6/20/2028
1998,EMPLOYED,25_34,high school,Retail,mumbai,HIGH,22.000000,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,NaN,unknown,moderate,15.244898,43300.0,6/22/2028

In [ ]:
df.to_csv("cleaned_data.csv", index=False)