##  Chapter 1

## Data Manipulation with Pandas

# 1. Series

In [ ]:
import pandas as pd    # alies  (as)

In [ ]:
Marks=[90,91,92,93,94,94]
ds=pd.Series(Marks)
print(ds)
print(type(ds))

0    90
1    91
2    92
3    93
4    94
5    94
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
#customized index
Marks=[90,91,92,93,94,94]
ds=pd.Series(Marks,index=['a','b','c','d','e','f'])


print(ds)

a    90
b    91
c    92
d    93
e    94
f    94
dtype: int64

In [ ]:
Marks=[90,91,92,93,94,94]
ds=pd.Series(Marks,index=['a','b','c','d','e'])  #  Length of values (6) does not match length of index (5)


print(ds)

ValueError: Length of values (6) does not match length of index (5)

In [ ]:
Marks=[90,91,92,93,94,94]
ds=pd.Series(Marks,index=['a','b','c','d','e','f','g'])#ValueError: Length of values (6) does not match length of index (7)


print(ds)

ValueError: Length of values (6) does not match length of index (7)

In [ ]:
Marks=[90,91,92,93,94,94]
ds=pd.Series(Marks,index=['a','b','c','d','e','f'],dtype=float)


print(ds)

a    90.0
b    91.0
c    92.0
d    93.0
e    94.0
f    94.0
dtype: float64

In [ ]:
# add file name
Marks=[90,91,92,93,94,94]
ds=pd.Series(Marks,index=['a','b','c','d','e','f'],dtype=float,name="marksheet")


print(ds)

a    90.0
b    91.0
c    92.0
d    93.0
e    94.0
f    94.0
Name: marksheet, dtype: float64

## 1.1 Common Operation

In [ ]:
#sum
print(ds.sum())

#min
print("min no in series: ",ds.min())

#max
print("max no in series: ",ds.max())

#mean
print("mean of series: ", ds.mean())

554.0
min no in series:  90.0
max no in series:  94.0
mean of series:  92.33333333333333

## 1.2 Indexing and Slicing

In [ ]:
print("access elemnet by int",ds["a"])

access elemnet by int 90.0

In [ ]:
print("access elemnet by variable",ds[2])

access elemnet by variable 92.0

/tmp/ipykernel_2857/293275464.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("access elemnet by variable",ds[2])

In [ ]:
print("Slicing in Series",ds[0:3])

Slicing in Series a    90.0
b    91.0
c    92.0
Name: marksheet, dtype: float64

In [ ]:
print("Slicing in Series",ds['a':'d'])

Slicing in Series a    90.0
b    91.0
c    92.0
d    93.0
Name: marksheet, dtype: float64

## 1.3 Vectorized Operations

In [ ]:
print(ds+5)

print(ds*1)

print(ds/1)

print(ds%1)

print(ds**1)

a    95.0
b    96.0
c    97.0
d    98.0
e    99.0
f    99.0
Name: marksheet, dtype: float64
a    90.0
b    91.0
c    92.0
d    93.0
e    94.0
f    94.0
Name: marksheet, dtype: float64
a    90.0
b    91.0
c    92.0
d    93.0
e    94.0
f    94.0
Name: marksheet, dtype: float64
a    0.0
b    0.0
c    0.0
d    0.0
e    0.0
f    0.0
Name: marksheet, dtype: float64
a    90.0
b    91.0
c    92.0
d    93.0
e    94.0
f    94.0
Name: marksheet, dtype: float64

dictionary can be a series

In [ ]:
info={
    "name" : "Pragya",
    "age":21
}
ds1=pd.Series(info)
print(ds1)

name    Pragya
age         21
dtype: object

In [ ]:
ds1['name']

'Pragya'

In [ ]:
ds1.index

Index(['name', 'age'], dtype='object')

# Create a series with single digit

In [ ]:
num=pd.Series(5)
print(num)

0    5
dtype: int64

In [ ]:
num=pd.Series(5,index=[1,2,3,4,5])
print(num)

#'we can  create multiple index with single value'

1    5
2    5
3    5
4    5
5    5
dtype: int64

In [ ]:
num=pd.Series(5,index=[1,2,3,4,5])
num1=pd.Series(10,index=[1,2,3,4,5])
print(num+num1)

1    15
2    15
3    15
4    15
5    15
dtype: int64

In [ ]:
# addiotn on basis of index
num=pd.Series(5,index=[1,2,3,4,5])
num1=pd.Series(10,index=[0,6,3,4,5])
print(num+num1)

#nan = not a number
'''same index  additon will perform
but in case differnet index it will show NaN
'''

0     NaN
1     NaN
2     NaN
3    15.0
4    15.0
5    15.0
6     NaN
dtype: float64

'same index  additon will perform\nbut in case differnet index it will show NaN\n'

In [ ]:
'''# different index it will show NaN
#indexing should be same'''
num=pd.Series(5,index=[1,2,3,4,5])
num1=pd.Series(10,index=['a','b','c','d','e'])
print(num+num1)

1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
dtype: float64

## 2. main data structure

## Pandas DataFrame

In [ ]:
import pandas as pd

In [ ]:
student={
    'Name':['Pragya','Payal','Niahrika'],
    'Roll no.':[70,67,62],
    'Marks':[92,93,95]
}

df=pd.DataFrame(student)
print(df)

       Name  Roll no.  Marks
0    Pragya        70     92
1     Payal        67     93
2  Niahrika        62     95

In [ ]:
# All arrays must be of the same length
student={
    'Name':['Pragya','Payal','Niahrika'],
    'Roll no.':[70,67,62],
    'Marks':[93,95]    #ValueError: All arrays must be of the same length
}

df=pd.DataFrame(student)
print(df)

ValueError: All arrays must be of the same length

In [ ]:
student={
    'Name':['Pragya','Payal','Niahrika'],
    'Roll no.':[70,67,62],
    'Marks':[92,93,95]
}

df=pd.DataFrame(student)
print(df)

       Name  Roll no.  Marks
0    Pragya        70     92
1     Payal        67     93
2  Niahrika        62     95

In [ ]:
# Creating a dataframe with list

student_info=[['a','b','c'],[20,30,40]]
df=pd.DataFrame(student_info)
df
#print(df)

    0   1   2
0   a   b   c
1  20  30  40

In [ ]:
 #Creating dataframe with multiple series

 SR={
     'Name':pd.Series(['Pragya','Niharika','Payal']),
     'Roll no':pd.Series([70,67,62])
 }
 df=pd.DataFrame(SR)
df

       Name  Roll no
0    Pragya       70
1  Niharika       67
2     Payal       62

## 2.1 Arithmetic Ooeartions

In [ ]:

var=pd.DataFrame({'A':[1,2,3],'B':[3,5,6]})
var

   A  B
0  1  3
1  2  5
2  3  6

In [ ]:
var["C"]=var['A']+var['B']
var

   A  B  C
0  1  3  4
1  2  5  7
2  3  6  9

## 2.3 SORTING

In [ ]:
#filter
var['Python']=var["C"]>10
var

   A  B  C  Python
0  1  3  4   False
1  2  5  7   False
2  3  6  9   False

# Handling missing values

In [ ]:
# create a dict. using np.NaN
#
import numpy as np
student={
    'Name':['Pragya','Payal','Niharika','Chhavi','Sarthak'],
    'Roll no.':[70,67,62,34,np.nan],
    'Marks':[92,93,np.nan,98,99],
    'Subject':['Chem',np.nan,'BIO',np.nan,'physics'],
    'City':['noida','noida','siwan',np.nan,np.nan]
}

df=pd.DataFrame(student)
df

       Name  Roll no.  Marks  Subject   City
0    Pragya      70.0   92.0     Chem  noida
1     Payal      67.0   93.0      NaN  noida
2  Niharika      62.0    NaN      BIO  siwan
3    Chhavi      34.0   98.0      NaN    NaN
4   Sarthak       NaN   99.0  physics    NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      5 non-null      object
 1   Roll no.  4 non-null      float64
 2   Marks     4 non-null      float64
 3   Subject   3 non-null      object
 4   City      3 non-null      object
dtypes: float64(2), object(3)
memory usage: 332.0+ bytes

In [ ]:
df.isnull()
#non null=false and null=true

    Name  Roll no.  Marks  Subject   City
0  False     False  False    False  False
1  False     False  False     True  False
2  False     False   True    False  False
3  False     False  False     True   True
4  False      True  False    False   True

In [ ]:
df.isnull().sum()

Name        0
Roll no.    1
Marks       1
Subject     2
City        2
dtype: int64

In [ ]:
print(df.isnull().sum().sum())

6

In [ ]:
df.dropna()

     Name  Roll no.  Marks Subject   City
0  Pragya      70.0   92.0    Chem  noida

In [ ]:
df['Marks']=df['Marks'].fillna(0)

In [ ]:
df.dropna(subset=['Roll no.'])

       Name  Roll no.  Marks Subject   City
0    Pragya      70.0   92.0    Chem  noida
1     Payal      67.0   93.0     NaN  noida
2  Niharika      62.0    0.0     BIO  siwan
3    Chhavi      34.0   98.0     NaN    NaN

In [ ]:
df['Marks']=df['Marks'].fillna(df['Marks'].mean())
print(df['Marks'])

0    92.0
1    93.0
2     0.0
3    98.0
4    99.0
Name: Marks, dtype: float64

In [ ]:
df['Name'].fillna("unknown")

0      Pragya
1       Payal
2    Niharika
3      Chhavi
4     Sarthak
Name: Name, dtype: object